apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app

    spec:
      serviceAccountName: shohag-build-bot
      containers:
        - name: maven-app
          image: shohagbkash/tekton-maven-test:latest
          ports:
            - containerPort: 8123
