apiVersion: v1
kind: Service
metadata:
  name: maven-svc
  labels:
    app: maven-app
spec:
  type: NodePort
  ports:
    - port: 8123
      targetPort: 8123
      nodePort: 32030
  selector:
    app: maven-app
